config/routes.rb
Rails.application.routes.draw do
  root to: "pages#dashboard"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :groups
  resources :group_members, only: [:create, :update]
  put "toggle_member_status", to: "group_members#toggle_status"
  resources :invitations

  resources :events
  resources :tasks
  put "toggle_task_complete", to: "tasks#toggle_complete"


  get "/sandbox", to: "sandbox#index"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_members
  has_many :users, through: :group_members
  has_many :invitations
  has_many :events
  has_many :tasks

  enum group_type: [:family]

  def admin?(user)
    member = group_members.where(user_id: user.id).first
    return false if member.blank?
    return true if member.admin?
    false
  end

  def add_admin(user)
    group_members.create(user_id: user.id, role: 0)
  end

  def add_member(user)
    group_members.create(user_id: user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_signed_in
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    if current_user.admin? 
      @groups = Group.all
    else
      @groups = current_user.groups
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    if @group.admin?(current_user)
      if @group.group_members.length > 0
        @members = @group.group_members.map { |m| { id: m.user_id, active: m.active, email: m.user.email }}
      else
        @members = []
      end
      @invitations = @group.invitations.unaccepted || []
    else
      redirect_to groups_path
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        code = SecureRandom.hex(6)
        @group.update(access_code: code)
        @group.add_admin(current_user)
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:title, :group_type)
    end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :group_type %>
    <%= select_tag :group_type, options_for_select(Group.group_types) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<%= render "components/page-title",
    title: "Groups", 
    actions: [{
      label: "New Group",
      href: new_group_path
    }]
  %>

  <% if current_user.admin? %>
    <p>As an administrator you can view all the groups.</p>
  <% end %>

  <% if @groups.length > 0 %>
    <div class="box-with-border">
      <% @groups.each do |group| %>
        <div class="list-item">
          <span><%= group.title %></span>

          <% if group.admin?(current_user) %>
            <%= link_to 'Members', group_path(group) %>
            <%= link_to 'Edit', edit_group_path(group) %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= render "components/page-empty",
      text: "You do not belong to any groups yet."
    %>
  <% end %>


  

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<%= render "components/page-title",
title: @group.title, 
actions: [{
  label: "Edit Group",
  href: edit_group_path(@group)
}]
%>

<%= react_component("AddGroupMembers", { 
    groupId: @group.id,
    userId: current_user.id, 
    members: @members,
    invitations: @invitations,
    groupCode: @group.access_code
  }) %>